#!/bin/bash
# NEXTFLOW TASK: modify_gctree_colors (m11_IGHV1-50*01_IGHJ3*01_39_2.aln)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /home/hieu/src/BCRTree_release/gctree/work/3e/2e54e64f8a38e893631dc37e9bf65a/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /home/hieu/src/BCRTree_release/gctree/work/3e/2e54e64f8a38e893631dc37e9bf65a/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f gctree.out.inference.1.fasta
    rm -f gctree.out.inference.1.nk
    rm -f gctree.out.inference.1.p
    rm -f gctree.out.inference.1.svg
    rm -f gctree.out.inference.abundance_rank.svg
    rm -f gctree.out.inference.parsimony_forest.p
    rm -f m11_IGHV1-50*01_IGHJ3*01_39_2.aln_dnapars.log
    rm -f outfile
    rm -f outtree
    rm -f m11_IGHV1-50*01_IGHJ3*01_39_2.aln.fasta
    rm -f m11_IGHV1-5001_IGHJ301_39_2.aln.id_map.csv
    rm -f m11_IGHV1-5001_IGHJ301_39_2.aln.id_map_seq.csv
    rm -f modify_tree_colors.py
    rm -f hex_color.csv
    ln -s /home/hieu/src/BCRTree_release/gctree/work/ff/0efc0211d87134233566958df42a3e/gctree.out.inference.1.fasta gctree.out.inference.1.fasta
    ln -s /home/hieu/src/BCRTree_release/gctree/work/ff/0efc0211d87134233566958df42a3e/gctree.out.inference.1.nk gctree.out.inference.1.nk
    ln -s /home/hieu/src/BCRTree_release/gctree/work/ff/0efc0211d87134233566958df42a3e/gctree.out.inference.1.p gctree.out.inference.1.p
    ln -s /home/hieu/src/BCRTree_release/gctree/work/ff/0efc0211d87134233566958df42a3e/gctree.out.inference.1.svg gctree.out.inference.1.svg
    ln -s /home/hieu/src/BCRTree_release/gctree/work/ff/0efc0211d87134233566958df42a3e/gctree.out.inference.abundance_rank.svg gctree.out.inference.abundance_rank.svg
    ln -s /home/hieu/src/BCRTree_release/gctree/work/ff/0efc0211d87134233566958df42a3e/gctree.out.inference.parsimony_forest.p gctree.out.inference.parsimony_forest.p
    ln -s /home/hieu/src/BCRTree_release/gctree/work/ff/0efc0211d87134233566958df42a3e/m11_IGHV1-50*01_IGHJ3*01_39_2.aln_dnapars.log m11_IGHV1-50*01_IGHJ3*01_39_2.aln_dnapars.log
    ln -s /home/hieu/src/BCRTree_release/gctree/work/ff/0efc0211d87134233566958df42a3e/outfile outfile
    ln -s /home/hieu/src/BCRTree_release/gctree/work/ff/0efc0211d87134233566958df42a3e/outtree outtree
    ln -s /home/hieu/src/BCRTree_release/gctree/example/m11_IGHV1-50*01_IGHJ3*01_39_2.aln.fasta m11_IGHV1-50*01_IGHJ3*01_39_2.aln.fasta
    ln -s /home/hieu/src/BCRTree_release/gctree/work/ac/347158b882f32697b81802d07ae9bc/m11_IGHV1-50*01_IGHJ3*01_39_2.aln.id_map.csv m11_IGHV1-5001_IGHJ301_39_2.aln.id_map.csv
    ln -s /home/hieu/src/BCRTree_release/gctree/work/ac/347158b882f32697b81802d07ae9bc/m11_IGHV1-50*01_IGHJ3*01_39_2.aln.id_map_seq.csv m11_IGHV1-5001_IGHJ301_39_2.aln.id_map_seq.csv
    ln -s /home/hieu/src/BCRTree_release/gctree/modify_tree_colors.py modify_tree_colors.py
    ln -s /home/hieu/src/BCRTree_release/gctree/hex_color.csv hex_color.csv
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/hieu/src/BCRTree_release/gctree/work/3e/2e54e64f8a38e893631dc37e9bf65a/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    nxf_stage

    set +e
    ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
